[PHP]

; Basic Settings
memory_limit = 1024M
max_execution_time = 60
max_input_time = 60
date.timezone = Europe/Amsterdam
default_charset = "UTF-8"

; Error Handling
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors = On
error_log = /dev/stderr

; File Uploads
file_uploads = On
upload_max_filesize = 50M
post_max_size = 50M
max_file_uploads = 20

; Session Settings
session.save_path = "/var/lib/php/sessions"
session.gc_maxlifetime = 86400 ; 1 day

; OPcache Settings (performance tuning)
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1 ; 0 for cache

; File Inclusion and Security
allow_url_fopen = On
